"""Role's Name should be unique

Revision ID: 3c6f60ab7464
Revises: fde2f1a5a9d0
Create Date: 2023-05-02 14:54:29.403648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c6f60ab7464'
down_revision = 'fde2f1a5a9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_role_name', table_name='role')
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.create_index('ix_role_name', 'role', ['name'], unique=False)
    # ### end Alembic commands ###
