"""Add cascade delete

Revision ID: fde2f1a5a9d0
Revises: 763e0411daf9
Create Date: 2023-05-02 12:32:14.003672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde2f1a5a9d0'
down_revision = '763e0411daf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bindings_role_id_fkey', 'bindings', type_='foreignkey')
    op.drop_constraint('bindings_user_id_fkey', 'bindings', type_='foreignkey')
    op.create_foreign_key(None, 'bindings', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bindings', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bindings', type_='foreignkey')
    op.drop_constraint(None, 'bindings', type_='foreignkey')
    op.create_foreign_key('bindings_user_id_fkey', 'bindings', 'user', ['user_id'], ['id'])
    op.create_foreign_key('bindings_role_id_fkey', 'bindings', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###
